# github actions workflow
# run on push to main branch if src/** or sites.yml files changed 
# run on pull request to main branch

name: Build Book and Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - '.github/**'
  pull_request:
    branches:
      - main
    paths:
      - 'src/**'
      - '.github/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install MdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: '0.4.21'
      - name: Build Book
        run: mdbook build

      # deploy if push to main branch
      - name: Deploy
        if: github.event_name == 'push'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book

